spring:
  application:
    name: eureka_server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    renewal-percent-threshold: 0.85